screen_width, screen_height = 1400, 800
resolution = screen_width, screen_height
fps = 60
player_speed = 0.002
player_rotation_speed = 0.007
player_pos = 2.5, 2.5
player_angle = 90
max_fruits = 5
colors = ["red", "orange", "yellow", "green", "cyan", "azure"]
